resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:37bf7ff12a35b8c183d08b439fb2a75da34a2f2cc156d9656b99cc642129690c
  name: controller
  newName: registry.redhat.io/rhtas/rhtas-rhel9-operator
