resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:8638159c41aff3234e965d9fd61a4fed9ae8393070228f6d4afd1124d186e970
  name: controller
  newName: registry.redhat.io/rhtas/rhtas-rhel9-operator
