resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:30f6c6666a8807362f70a7d01345d9cfaf92ce7e61d29ca3996cd4787b8b5229
  name: controller
  newName: quay.io/redhat-user-workloads/rhtas-tenant/operator/rhtas-operator
