resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:e550dad4a7299118fe220cd4c145c6e2deee75d2e28e41525f9dc2fb6c9f7508
  name: controller
  newName: quay.io/redhat-user-workloads/rhtas-tenant/operator/rhtas-operator
