apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: operator-controller-manager
  name: operator-controller-manager-metrics-service
spec:
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
  selector:
      control-plane: operator-controller-manager
