apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    control-plane: operator-controller-manager
  name: rhtas-operator-controller-manager-metrics-service
spec:
  ports:
  - name: metrics
    port: 8080
    targetPort: metrics
  selector:
    control-plane: operator-controller-manager
status:
  loadBalancer: {}
