apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-certificate
  namespace: ingress-nginx
spec:
  secretName: ingress-certificate
  commonName: "*.apps.DOMAIN"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - "*.apps.DOMAIN"
