apiVersion: rhtas.redhat.com/v1alpha1
kind: Securesign
metadata:
  labels:
    app.kubernetes.io/name: securesign
    app.kubernetes.io/instance: securesign-sample
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: securesign-sample
spec:
  rekor:
    external: true
    keySecret: rekor-private-key
    rekorCert:
      create: true
  fulcio:
    external: true
    keySecret: fulcio-secret-rh
    oidcIssuers:
      ? "https://keycloak-keycloak-system.apps.rosa.dzfgg-8asuc-oiz.9kks.p3.openshiftapps.com/auth/realms/sigstore"
      : ClientID: "sigstore"
        IssuerURL: "https://keycloak-keycloak-system.apps.rosa.dzfgg-8asuc-oiz.9kks.p3.openshiftapps.com/auth/realms/sigstore"
        Type: "email"
    fulcioCert:
      create: true
      organizationName: myOrg
      organizationEmail: myEmail
      certPassword: secure

  trillian:
  tuf:
    external: true
  ctlog:
